name: "Publish articles to Qiita"
description: "Publish articles to Qiita using qiita-cli"
author: "Qiita Inc."

inputs:
  root:
    required: false
    default: "."
    description: "Root directory path"
  qiita-token:
    required: true
    description: "Qiita API token"
  twitter-api-key: # TwitterのAPIキーを追加
    required: false
    description: "Twitter API key"
  twitter-api-secret: # TwitterのAPIシークレットを追加
    required: false
    description: "Twitter API secret"
  twitter-access-token: # Twitterのアクセス・トークンを追加
    required: false
    description: "Twitter access token"
  twitter-access-secret: # Twitterのアクセス・シークレットを追加
    required: false
    description: "Twitter access secret"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20.16.0"
    - name: Install qiita-cli
      run: npm install -g --verbose github:Pokeyama/qiita-cli#dev
      shell: bash
    - name: Debug
      run: ls -al
      shell: bash
    - name: Publish articles
      run: node dist/main.js publish --all --root ${{ inputs.root }}
      env:
        QIITA_TOKEN: ${{ inputs.qiita-token }}
        TWITTER_API_KEY: ${{ inputs.twitter-api-key }}
        TWITTER_API_SECRET: ${{ inputs.twitter-api-secret }}
        TWITTER_ACCESS_TOKEN: ${{ inputs.twitter-access-token }}
        TWITTER_ACCESS_SECRET: ${{ inputs.twitter-access-secret }}
      shell: bash
    - name: Commit and push diff # Not executed recursively even if `push` is triggered. See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
      run: |
        git add ${{ inputs.root }}/public/*
        if ! git diff --staged --exit-code --quiet; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m 'Updated by qiita-cli'
          git push
        fi
      shell: bash
